C *******************************************************************
C Parameter Declarations for the MTAMC Mode Choice Model
C                                Application Program
C
C *******************************************************************

      integer*2    MAX_ZONES,MAX_IZONES,MAX_STATIONS
C
C     LOS ANGELES MTA PARAMETERS (PHASE 2)
C ----------------------------------------------------------------          
       parameter(MAX_ZONES     = 5337)
       parameter(MAX_IZONES    = 4637)
       parameter(MAX_STATIONS  =  700)