C-------------------------------------------------------------------
C       STATION EGRESS TRIP MATRIX SUBROUTINE
C-------------------------------------------------------------------
      SUBROUTINE EGRTRP(JZ,IMODE,OSTA,ASTA,TRIPS,RALSTAZ,ALLSTAZ,
     *                  CHWIND,CHBKIND,CHBIND,CHPIND,CHKIND,
     *                  WDSTA,BIKDSTA,BDSTA,PDSTA,KDSTA,STAEGR,
     *                  RALWLK,ALLWLK)
      INCLUDE 'stadat.com'
      INCLUDE 'param.com'
      INCLUDE 'mtamcpar.inc'
C
      INTEGER*2 IMODE,ASTA(5,14)
      INTEGER*2 OSTA(5,14),JZ,SC,ISTA,IC,DC,SC2
      INTEGER*2 WDSTA(10,5),BIKDSTA(10,5)
      INTEGER*2 BDSTA(10,2),PDSTA(10,10)
      INTEGER*2 KDSTA(10,10)
      REAL*8    TRIPS(14)
      REAL*4    RALSTAZ(MAX_STATIONS,MAX_IZONES)
      REAL*4    ALLSTAZ(MAX_STATIONS,MAX_IZONES)
      REAL*4    RALWLK(MAX_STATIONS,MAX_IZONES)
      REAL*4    ALLWLK(MAX_STATIONS,MAX_IZONES)
      REAL*4    STAEGR(3,MAX_STATIONS,MAX_IZONES)
      LOGICAL   CHWIND(5,2),CHBKIND(5,2),CHBIND(5,2)
      LOGICAL   CHPIND(5,4),CHKIND(5,4)
C
C...WALK ACCESS STATIONS
      DO ISTA=1,2
      IF(CHWIND(IMODE,ISTA)) THEN
      SC2=WDSTA((IMODE+5),ISTA)-MAX_IZONES      
      ALLSTAZ(SC2,JZ)=ALLSTAZ(SC2,JZ)+
     *  (SNGL(TRIPS(ISTA))*STAEGR(2,SC2,JZ))
      ALLWLK(SC2,JZ)=ALLWLK(SC2,JZ)+
     *  (SNGL(TRIPS(ISTA))*STAEGR(1,SC2,JZ))
      ELSE
      SC=ASTA(IMODE,ISTA)-MAX_IZONES
      RALSTAZ(SC,JZ)=RALSTAZ(SC,JZ)+
     *  (SNGL(TRIPS(ISTA))*STAEGR(2,SC,JZ))
      RALWLK(SC,JZ)=RALWLK(SC,JZ)+
     *  (SNGL(TRIPS(ISTA))*STAEGR(1,SC,JZ))
      END IF
      END DO
C...BUS ACCESS STATIONS
      DO ISTA=1,2
      IF(CHBIND(IMODE,ISTA)) THEN
      SC2=BDSTA((IMODE+5),ISTA)-MAX_IZONES      
      ALLSTAZ(SC2,JZ)=ALLSTAZ(SC2,JZ)+
     *   (SNGL(TRIPS(ISTA+2))*STAEGR(2,SC2,JZ))
      ALLWLK(SC2,JZ)=ALLWLK(SC2,JZ)+
     *   (SNGL(TRIPS(ISTA+2))*STAEGR(1,SC2,JZ))
      ELSE
      SC=ASTA(IMODE,(ISTA+2))-MAX_IZONES
      RALSTAZ(SC,JZ)=RALSTAZ(SC,JZ)+
     *   (SNGL(TRIPS(ISTA+2))*STAEGR(2,SC,JZ))
      RALWLK(SC,JZ)=RALWLK(SC,JZ)+
     *   (SNGL(TRIPS(ISTA+2))*STAEGR(1,SC,JZ))
      END IF
      END DO
C...PNR ACCESS STATIONS
      DO ISTA=1,4
      IF(CHPIND(IMODE,ISTA)) THEN
      SC2=PDSTA((IMODE+5),ISTA)-MAX_IZONES      
      ALLSTAZ(SC2,JZ)=ALLSTAZ(SC2,JZ)+
     *   (SNGL(TRIPS(ISTA+4))*STAEGR(2,SC2,JZ))
      ALLWLK(SC2,JZ)=ALLWLK(SC2,JZ)+
     *   (SNGL(TRIPS(ISTA+4))*STAEGR(1,SC2,JZ))
      ELSE
      SC=ASTA(IMODE,(ISTA+4))-MAX_IZONES
      RALSTAZ(SC,JZ)=RALSTAZ(SC,JZ)+
     *   (SNGL(TRIPS(ISTA+4))*STAEGR(2,SC,JZ))
      RALWLK(SC,JZ)=RALWLK(SC,JZ)+
     *   (SNGL(TRIPS(ISTA+4))*STAEGR(1,SC,JZ))
      END IF
      END DO
C...KNR ACCESS STATIONS
      DO ISTA=1,4
      IF(CHKIND(IMODE,ISTA)) THEN
      SC2=KDSTA((IMODE+5),ISTA)-MAX_IZONES      
      ALLSTAZ(SC2,JZ)=ALLSTAZ(SC2,JZ)+
     *   (SNGL(TRIPS(ISTA+8))*STAEGR(2,SC2,JZ))
      ALLWLK(SC2,JZ)=ALLWLK(SC2,JZ)+
     *   (SNGL(TRIPS(ISTA+8))*STAEGR(1,SC2,JZ))
      ELSE
      SC=ASTA(IMODE,(ISTA+8))-MAX_IZONES
      RALSTAZ(SC,JZ)=RALSTAZ(SC,JZ)+
     *   (SNGL(TRIPS(ISTA+8))*STAEGR(2,SC,JZ))
      RALWLK(SC,JZ)=RALWLK(SC,JZ)+
     *   (SNGL(TRIPS(ISTA+8))*STAEGR(1,SC,JZ))
      END IF
      END DO
C...BIKE ACCESS STATIONS
      DO ISTA=1,2
      IF(CHBKIND(IMODE,ISTA)) THEN
      SC2=BIKDSTA((IMODE+5),ISTA)-MAX_IZONES      
      ALLSTAZ(SC2,JZ)=ALLSTAZ(SC2,JZ)+
     *   (SNGL(TRIPS(ISTA+12))*STAEGR(2,SC2,JZ))
      ALLWLK(SC2,JZ)=ALLWLK(SC2,JZ)+
     *   (SNGL(TRIPS(ISTA+12))*STAEGR(1,SC2,JZ))
      ELSE
      SC=ASTA(IMODE,(ISTA+12))-MAX_IZONES
      RALSTAZ(SC,JZ)=RALSTAZ(SC,JZ)+
     *   (SNGL(TRIPS(ISTA+12))*STAEGR(2,SC,JZ))
      RALWLK(SC,JZ)=RALWLK(SC,JZ)+
     *   (SNGL(TRIPS(ISTA+12))*STAEGR(1,SC,JZ))
      END IF
      END DO           
      RETURN
      END
