C-------------------------------------------------
C     NHB DIRECT DEMAND MODEL
C     TRIP GENERATION APPLICATION
C-------------------------------------------------
      SUBROUTINE NHBGEN(NHBACC,SSDIST,ZHHD,NHBTRP)
      INCLUDE 'param.com'
      INCLUDE 'stadat.com'
      INCLUDE 'mtamcpar.inc'
      INTEGER*4     SC,SC2,ATRZNE
      REAL*4        NHBACC(MAX_STATIONS,MAX_STATIONS)
      REAL*4        SSDIST(MAX_STATIONS,MAX_STATIONS)
      REAL*4        ZHHD(30,MAX_IZONES)
      REAL*4        RETAIL,ACCIJ,TACCIJ,UACCESS
      REAL*4        WTIME,WACCIJ,TWACCIJ,WACCESS,TRATE
      REAL*4        WBOP,WBOA,WTW,OTO,TSUM(5)
      REAL*4        THBO,ZHBO,XHBO,NHBTRP(MAX_STATIONS,4)
C
      WRITE(*,8000)
 8000 FORMAT(1X,'NHB Direct Demand Model Trip Generation')
C 
C     SUMMARIZE STATION LEVEL TRIP GENERATION RESULTS
C
      WRITE(26,9003)
 9003 FORMAT(//,30X,'R E P O R T   22',/,
     *          20X,
     *          '        NHB DIRECT DEMAND MODEL'/
     *          20X,
     *          'SUMMARIZE TRIP GENERATION RESULTS',//,
     *       1X,' STATION ','                              ',
     *          '  WBO   ','   WBO  ','  WTW   ','   OTO  '/
     *       1X,' NUMBER ','        STATION NAME           ',
     *          '  PRODS ','  ATTRS ','  ENDS  ','   ENDS '/
     *       1X,'--------','-------------------------------',
     *          '--------','--------','--------','---------')
C
C.....COMPUTE OVERALL TRANSIT AND WALK ACCESSIBILITY VALUE 
C     FOR EACH PRODUCTION STATION
C
      DO 100 SC=1,MAX_STATIONS
C
      TACCIJ=0.0
      TWACCIJ=0.0
      THBO=0.0
      ZHBO=0.0
      IF(STANUM(SC).NE.2.OR.STADATA(SC,6).NE.1) GO TO 100
C
      DO 200 SC2=1,MAX_STATIONS
C
      IF(STANUM(SC2).NE.2.OR.STADATA(SC2,6).NE.1) GO TO 200
      IF(SC.EQ.SC2) GO TO 200
      IF(NHBACC(SC,SC2).LE.0) GO TO 200
      ATRZNE=ZNENHB(SC2)
      IF(ATRZNE.LE.0.OR.ATRZNE.GT.MAX_IZONES) THEN
      WRITE(26,201) ATRZNE,(SC2+MAX_IZONES)
  201 FORMAT(' NHBGEN 201 (F) ATTRACTION ZONE=',I4,' FOR STATION=',I4,
     *       ' OUTSIDE EXPECTED RANGE')
      STOP 201
      END IF
      RETAIL=ZHHD(18,ATRZNE)
C --- TRANSIT
      ACCIJ=RETAIL*EXP(-0.05*NHBACC(SC,SC2))
      TACCIJ=TACCIJ+ACCIJ
C --- WALK
      WTIME=20.0*SSDIST(SC,SC2)
      WACCIJ=RETAIL*EXP(-0.05*2.0*WTIME)
      TWACCIJ=TWACCIJ+WACCIJ
C --- HBO ATTRACTIONS WITHIN 1 MILE DISTANCE
      IF(SSDIST(SC,SC2).LE.1.0) THEN
      THBO=THBO+STANHB(SC2,4)
      ZHBO=ZHBO+1
      END IF
      IF(SDETAIL) WRITE(26,9001) (SC+MAX_IZONES),(SC2+MAX_IZONES),
     *               ATRZNE,RETAIL,
     *               NHBACC(SC,SC2),ACCIJ,TACCIJ,
     *               SSDIST(SC,SC2),WTIME,WACCIJ,TWACCIJ,
     *               THBO,ZHBO
 9001 FORMAT(' FROM STATION=',I4,' TO STATION=',I4,' CLOSEST ZONE=',I4,
     *       ' RETAIL EMP=',F6.0,' URBAN RAIL ACCESS=',F6.2,
     *       ' ACCESS TERM=',F9.2,' CUMULATIVE ACCESS TERM=',F9.2/
     *       ' STATION-TO-STATIION DIST=',F6.2,' WTIME=',F6.2,
     *       ' WALK ACCESS TERM=',F9.2,' CUMULATIVE WALK ACCESS TERM=',
     *         F9.2,' HBO ATTRS WITH 1 MI=',F10.1,
     *       ' NUMBER OF STATIONS=',F4.0)
  200 CONTINUE
      IF(ZHBO.GT.0.AND.SDETAIL) WRITE(26,9006) (SC+MAX_IZONES),ZHBO,THBO
 9006 FORMAT(' STA=',I4,' NO OF STATIONS=',F4.0,' HBO ATTRS=',F10.1)
      UACCESS=ALOG(TACCIJ)
      WACCESS=ALOG(TWACCIJ)
      UACCESS=AMAX1(UACCESS,0.0)
      WACCESS=AMAX1(WACCESS,0.0)
C
C     WBO PRODUCTIONS
C
      TRATE=(0.028*UACCESS)-0.002*(UACCESS*WACCESS)-0.064
      WBOP=STANHB(SC,3)*TRATE
      IF(SDETAIL) WRITE(26,9002) (SC+MAX_IZONES),UACCESS,WACCESS,
     *            TRATE,WBOP
 9002 FORMAT(' STATION=',I4,' UACCESS=',F8.2,' WACCESS=',F8.2,
     *       ' TRATE=',F6.4,' WBO PRODUCTIONS=',F7.2)
C
C     WBO ATTRACTIONS
C
      IF(ZHBO.GT.0) THEN
      XHBO=(THBO/ZHBO)-STANHB(SC,4)
      ELSE
      XHBO=0.0
      END IF
      XHBO=AMAX1(XHBO,0.0)
      TRATE=0.012*WACCESS+0.0000048*XHBO-0.029
      TRATE=AMAX1(TRATE,0.0)
      WBOA=TRATE*STANHB(SC,4)*ARATIO+0.014*STANHB(SC,1)
      IF(SDETAIL) WRITE(26,9007) (SC+MAX_IZONES),THBO,ZHBO,
     *               STANHB(SC,4),XHBO,TRATE,
     *               ARATIO,WBOA
 9007 FORMAT(' STATION=',I4,' THB0=',F7.1,' ZHBO=',F4.0,
     *       ' STANHB=',F7.1,
     *       ' XHBO=',F8.1,' TRATE=',F6.4,' ARATIO=',F6.4,
     *       ' WBOA=',F8.1)
C
C     WTW TRIP ENDS
C 
      IF(STANHB(SC,3).GT.0) THEN
      TRATE=STANHB(SC,5)/STANHB(SC,3)
      ELSE
      TRATE=0.0
      END IF
      TRATE=0.163*TRATE-0.010
      TRATE=AMAX1(TRATE,0.0)
      WTW=TRATE*STANHB(SC,3)+0.043*STANHB(SC,1)
      IF(SDETAIL) WRITE(26,9008) (SC+MAX_IZONES),TRATE,STANHB(SC,3),
     *               STANHB(SC,5),STANHB(SC,1),WTW
 9008 FORMAT(' STATION=',I4,' TRATE=',F6.4,' HBW ATTR=',F8.1,
     *       ' HBW ATTR >50K=',F8.1,' HBW PRODS=',F8.1,
     *       ' WTW=',F8.1)
C
C     OTO TRIP ENDS
C
      OTO=0.184*STANHB(SC,4)+0.045*STANHB(SC,2)
C
C     STORE TRIP END DATA
C
      NHBTRP(SC,1)=WBOP
      NHBTRP(SC,2)=WBOA
      NHBTRP(SC,3)=WTW
      NHBTRP(SC,4)=OTO
C
C     WRITE TRIP GENERATION VALUES
C
      TSUM(1)=TSUM(1)+WBOP
      TSUM(2)=TSUM(2)+WBOA
      TSUM(3)=TSUM(3)+WTW
      TSUM(4)=TSUM(4)+OTO
      WRITE(26,9004) (SC+MAX_IZONES),STANAME(SC),WBOP,WBOA,WTW,OTO
 9004 FORMAT(2X,I4,3X,A29,1X,4F8.0)
  100 CONTINUE
      WRITE(26,9005) (TSUM(K),K=1,4)
 9005 FORMAT(/3X,'TOTAL',31X,4F8.0)
      TSUM(5)=TSUM(1)/TSUM(2)
      DO SC=1,MAX_STATIONS
      NHBTRP(SC,2)=NHBTRP(SC,2)*TSUM(5)
      END DO
      RETURN
      END
