C-------------------------------------------------------------------
C       STORE STATION TO STATION MATRIX VALUES
C-------------------------------------------------------------------
      SUBROUTINE STSSUM(IMODE,OSTA,ASTA,TRIPS,RALSS,ALLSS,
     *                  CHWIND,CHBKIND,CHBIND,CHPIND,CHKIND,
     *                  WDSTA,BIKDSTA,BDSTA,PDSTA,KDSTA,LSHARE)
      INCLUDE 'stadat.com'
      INCLUDE 'param.com'
      INCLUDE 'mtamcpar.inc'
C
      INTEGER*2 IMODE,ASTA(5,14)
      INTEGER*2 OSTA(5,14),JZ,SC,ISTA,IC,DC,SC2
      INTEGER*2 WDSTA(10,5),BIKDSTA(10,5)
      INTEGER*2 BDSTA(10,2),PDSTA(10,10)
      INTEGER*2 KDSTA(10,10)
      REAL*4    RALSS(MAX_STATIONS,MAX_STATIONS)
      REAL*4    ALLSS(MAX_STATIONS,MAX_STATIONS)
      REAL*8    TRIPS(14),LSHARE
      LOGICAL   CHWIND(5,2),CHBKIND(5,2),CHBIND(5,2)
      LOGICAL   CHPIND(5,4),CHKIND(5,4)
C
C   SCALE LOW INCOME IF NCATS EQ 1
      IF(LOWRAIL.AND.(NCATS.EQ.1).AND.(LSHARE.LE.1.0)) THEN
      DO K=1,14
      TRIPS(K)=TRIPS(K)*LSHARE
      END DO
      END IF
C
C...WALK ACCESS STATIONS
      DO ISTA=1,2
      DC=OSTA(IMODE,ISTA)-MAX_IZONES
      SC=ASTA(IMODE,ISTA)-MAX_IZONES
      IF(CHWIND(IMODE,ISTA)) THEN
      SC2=WDSTA((IMODE+5),ISTA)-MAX_IZONES  
      ALLSS(DC,SC2)=ALLSS(DC,SC2)+SNGL(TRIPS(ISTA))
      ELSE
      RALSS(DC,SC)=RALSS(DC,SC)+SNGL(TRIPS(ISTA))
      END IF
      END DO
C...BUS ACCESS STATIONS
      DO ISTA=1,2
      DC=OSTA(IMODE,(ISTA+2))-MAX_IZONES
      SC=ASTA(IMODE,(ISTA+2))-MAX_IZONES
      IF(CHBIND(IMODE,ISTA)) THEN
      SC2=BDSTA((IMODE+5),ISTA)-MAX_IZONES  
      ALLSS(DC,SC2)=ALLSS(DC,SC2)+SNGL(TRIPS(ISTA+2))
      ELSE
      RALSS(DC,SC)=RALSS(DC,SC)+SNGL(TRIPS(ISTA+2))
      END IF
      END DO
C...PNR ACCESS STATIONS
      DO ISTA=1,4
      DC=OSTA(IMODE,(ISTA+4))-MAX_IZONES
      SC=ASTA(IMODE,(ISTA+4))-MAX_IZONES
      IF(CHPIND(IMODE,ISTA)) THEN
      SC2=PDSTA((IMODE+5),ISTA)-MAX_IZONES  
      ALLSS(DC,SC2)=ALLSS(DC,SC2)+SNGL(TRIPS(ISTA+4))
      ELSE
      RALSS(DC,SC)=RALSS(DC,SC)+SNGL(TRIPS(ISTA+4))
      END IF
      END DO
C...KNR ACCESS STATIONS
      DO ISTA=1,4
      DC=OSTA(IMODE,(ISTA+8))-MAX_IZONES
      SC=ASTA(IMODE,(ISTA+8))-MAX_IZONES
      IF(CHKIND(IMODE,ISTA)) THEN
      SC2=KDSTA((IMODE+5),ISTA)-MAX_IZONES  
      ALLSS(DC,SC2)=ALLSS(DC,SC2)+SNGL(TRIPS(ISTA+8))
      ELSE
      RALSS(DC,SC)=RALSS(DC,SC)+SNGL(TRIPS(ISTA+8))
      END IF
      END DO
C...BIKE ACCESS STATIONS
      DO ISTA=1,2
      DC=OSTA(IMODE,(ISTA+12))-MAX_IZONES
      SC=ASTA(IMODE,(ISTA+12))-MAX_IZONES
      IF(CHBKIND(IMODE,ISTA)) THEN
      SC2=BIKDSTA((IMODE+5),ISTA)-MAX_IZONES  
      ALLSS(DC,SC2)=ALLSS(DC,SC2)+SNGL(TRIPS(ISTA+12))
      ELSE
      RALSS(DC,SC)=RALSS(DC,SC)+SNGL(TRIPS(ISTA+12))
      END IF
      END DO
      RETURN
      END
