C *******************************************************************
C Parameter Declarations for the MTAMC Mode Choice Model
C                                Application Program
C
C *******************************************************************

      integer*2    MAX_ZONES,MAX_IZONES,MAX_STATIONS
C ----------------------------------------------------------------
C     LOS ANGELES MTA PARAMETERS (WSAB)
C ----------------------------------------------------------------          
C      parameter(MAX_ZONES     = 3800)
C      parameter(MAX_IZONES    = 3057)
C      parameter(MAX_STATIONS  = 743)
C ----------------------------------------------------------------
C     LOS ANGELES MTA PARAMETERS (PHASE II)
C ----------------------------------------------------------------          
       parameter(MAX_ZONES     = 5337)
       parameter(MAX_IZONES    = 4597)
       parameter(MAX_STATIONS  = 740)