C-------------------------------------------------------------------
C        CREATE RAIL INDICATOR MATRIX
C-------------------------------------------------------------------
       SUBROUTINE RAILINDC(STAINDC,STAINDC2,STAINDC3)
       INCLUDE 'stadat.com'
       INCLUDE 'param.com'
       include 'tpcom.inc'
       include 'control.inc'
       include 'mtamcpar.inc'
C
C DATA DECLARATIONS
C
      INTEGER*2     STAINDC(MAX_STATIONS,MAX_STATIONS)
      INTEGER*2     STAINDC2(MAX_ZONES,MAX_STATIONS)
      INTEGER*2     STAINDC3(MAX_STATIONS,MAX_ZONES)
      INTEGER*2     SC,IC,SC2,DC
C
C  URBAN RAIL STATION TO STATION INDICATOR
C
      CALL PREPIO(RALIND,11)
C
C  ORIGIN STATION LOOP 
C
      DO 50 SC=1,MAX_STATIONS
      IC=SC+MAX_IZONES
      PURP=1
      call intab(11,VAR,ic,PURP,dummy,io)
C
C   DESTINATION STATION LOOP
C
      DO 60 SC2=1,MAX_STATIONS
      DC=SC2+MAX_IZONES
      STAINDC(SC,SC2)=VAR(DC)
   60 CONTINUE
   50 CONTINUE
      CLOSE(11,STATUS='KEEP')
C
C  COMMUTER RAIL ZONE TO STATION INDICATOR
C
      CALL PREPIO(RALIND,11)
      DO 150 IC=1,MAX_IZONES
      PURP=2
      CALL INTAB(11,VAR,IC,PURP,DUMMY,IO)
      DO 160 SC2=1,MAX_STATIONS
      DC=SC2+MAX_IZONES
      STAINDC2(IC,SC2)=VAR(DC)
  160 CONTINUE
  150 CONTINUE
      CLOSE(11,STATUS='KEEP')
C
C COMMUTER RAIL STATION TO ZONE INDICATOR
C
      CALL PREPIO(RALIND,11)
      DO 250 SC=1,MAX_STATIONS
      IC=SC+MAX_IZONES
      PURP=2
      CALL INTAB(11,VAR,IC,PURP,DUMMY,IO)  
      DO 260 DC=1,MAX_IZONES
      STAINDC3(SC,DC)=VAR(DC)
  260 CONTINUE
  250 CONTINUE
      CLOSE(11,STATUS='KEEP')
C
C   OPEN USERBENC FILE
C
      OPEN(11,FILE='USERBENC1.MTX',STATUS='UNKNOWN',
     *        FORM='UNFORMATTED')
      NUMPUR=96
      TABLES=2**15-1
      WRITE(11) HEAD1,HEAD2
      NUMPUR=104
      OPEN(70,FILE='USERBENC2.MTX',STATUS='UNKNOWN',
     *        FORM='UNFORMATTED')
      WRITE(70) HEAD1,HEAD2
      RETURN
      END
