C-------------------------------------------------------------------
C     URBAN & COMMUTER RAIL BEST PATH INFO SUBROUTINE
C-------------------------------------------------------------------   
      SUBROUTINE RAILPATH(JZ,STA,DSTA,IMODE,VALUES,STAZONE,CDSTABRT,
     *                    STASTAD,STAZNED)
	    INCLUDE 'param.com'
	    include 'mtamcpar.inc'
      integer*2     jz,imode,SMODE,SJZ
      INTEGER*2     STA,DS,DSTA,ic,dc,sic,sdc,CDSTABRT,QSTA
      INTEGER*4     STAZONE(MAX_STATIONS,MAX_IZONES,2)
	    REAL*4        VALUES(15)
      REAL*4        WAIT1,WAIT2,
     *              TRANSF,FARE,WALKACC,INVEH,
     *              TIVT,WALKEGR,WALKTFR,
     *              SELUTL,STAUTL 
      REAL*4        INVEHL,INVEHR,INVEHE,INVEHT,INVEHB,INVEHU
      REAL*4        EGRTIME
      REAL*4        LHIVTJ,INVEHJ,WAIT1J,WAIT2J,
     *               TRANSFJ,FAREJ,WALKACCJ,
     *               WALKEGRJ,WALKTFRJ,SELUTLJ,STAUTLJ 
      REAL*4        STASTAD(3,13,BMAX_STATIONS,BMAX_STATIONS)
      REAL*4        STAZNED(5,19,BMAX_STATIONS,BMAX_IZONES)       
      IF(STA.EQ.MAX_ZONES.OR.DSTA.EQ.MAX_ZONES) RETURN
      IF(STA.LE.0.OR.DSTA.LE.0) RETURN
      QSTA=STA
C
C OBTAIN BRT STATION TO URBAN RAIL STATION DETAILS
C
      IF(IMODE.EQ.5) THEN
      SIC=STA-MAX_IZONES
      SDC=CDSTABRT-MAX_IZONES
      VALUES(1)=STASTAD(3,2,SIC,SDC)
      VALUES(2)=STASTAD(3,3,SIC,SDC)
      VALUES(3)=STASTAD(3,4,SIC,SDC)
      VALUES(6)=STASTAD(3,6,SIC,SDC)
      VALUES(7)=STASTAD(3,7,SIC,SDC)
      VALUES(13)=STASTAD(3,5,SIC,SDC)
      VALUES(15)=STASTAD(3,1,SIC,SDC)
  280 IMODE=2
      QSTA=CDSTABRT
      END IF
C 
C OBTAIN STATION-TO-STATION DETAILS 
C
      SIC=QSTA-MAX_IZONES
      SDC=DSTA-MAX_IZONES
      WAIT1=STASTAD(IMODE,1,SIC,SDC)
      WAIT2=STASTAD(IMODE,2,SIC,SDC)
      TRANSF=STASTAD(IMODE,3,SIC,SDC)
      FARE=STASTAD(IMODE,4,SIC,SDC)
      WALKACC=STASTAD(IMODE,5,SIC,SDC)
      INVEH=STASTAD(IMODE,6,SIC,SDC)
      TIVT=STASTAD(IMODE,7,SIC,SDC)
      WALKEGR=STASTAD(IMODE,8,SIC,SDC)
      WALKTFR=STASTAD(IMODE,9,SIC,SDC)
C
C OBTAIN STATION-TO-ZONE DETAILS
C
      EGRTIME=STAZONE((DSTA-MAX_IZONES),JZ,1)/100.0
      SIC=DSTA-MAX_IZONES
      LHIVTJ=STAZNED(IMODE,1,SIC,JZ)
      INVEHJ=STAZNED(IMODE,2,SIC,JZ)
      WAIT1J=STAZNED(IMODE,3,SIC,JZ)
      WAIT2J=STAZNED(IMODE,4,SIC,JZ)
      TRANSFJ=STAZNED(IMODE,5,SIC,JZ)
      FAREJ=STAZNED(IMODE,6,SIC,JZ)
      WALKACCJ=STAZNED(IMODE,7,SIC,JZ)
      WALKEGRJ=STAZNED(IMODE,8,SIC,JZ)
      WALKTFRJ=STAZNED(IMODE,9,SIC,JZ)
      INVEHL=STAZNED(IMODE,10,SIC,JZ)
      INVEHR=STAZNED(IMODE,11,SIC,JZ)
      INVEHE=STAZNED(IMODE,12,SIC,JZ)
      INVEHT=STAZNED(IMODE,13,SIC,JZ)
      INVEHB=STAZNED(IMODE,14,SIC,JZ)
      INVEHU=STAZNED(IMODE,15,SIC,JZ)
C         
      VALUES(1)=WAIT1+VALUES(1)
      VALUES(2)=WAIT2+WAIT1J+WAIT2J+VALUES(2)
      VALUES(3)=TRANSF+TRANSFJ+VALUES(3)
      VALUES(4)=WALKACC
      VALUES(5)=0.0
      VALUES(6)=WALKEGRJ+EGRTIME+VALUES(6)
      VALUES(7)=WALKEGR+WALKACCJ+WALKTFR+WALKTFRJ+VALUES(7)
      VALUES(8)=INVEHL
      VALUES(9)=INVEHE
      VALUES(10)=INVEHT
      VALUES(11)=0.0
      IF(IMODE.EQ.1) VALUES(11)=INVEHU
      IF(IMODE.EQ.2.OR.IMODE.EQ.5) VALUES(11)=INVEH+LHIVTJ
      VALUES(12)=0.0
      IF(IMODE.EQ.1) VALUES(12)=INVEH+LHIVTJ
      VALUES(13)=FARE+FAREJ+VALUES(13)
      VALUES(14)=INVEHR
      VALUES(15)=INVEHB+VALUES(15)
  400 CONTINUE
C ---------------------------------------------------------------------
      IF(DEBUG.AND.BESTPATH) THEN
      WRITE(26,9001) JZ,STA,DSTA,IMODE,VALUES
 9001 FORMAT(/1X,'RAILPATH SUBROUTINE COMPUTATIONS'/
     *        1X,'-----------------------------'/
     *        1X,'DESTINATION ZONE    =',I12/
     *        1X,'ORIGIN STATION      =',I12/
     *        1X,'DESTINATION STATION =',I12/
     *        1X,'IMODE               =',I12/
     *        1X,'FIRST WAIT          =',F12.2/
     *        1X,'TRANSFER WAIT       =',F12.2/
     *        1X,'TRANSFERS           =',F12.2/
     *        1X,'WALK ACCESS         =',F12.2/
     *        1X,'DRIVE ACCESS        =',F12.2/
     *        1X,'WALK/DRIVE EGRESS   =',F12.2/
     *        1X,'TRANSFER WALK       =',F12.2/
     *        1X,'LOCAL BUS IVT       =',F12.2/
     *        1X,'EXPRESS BUS IVT     =',F12.2/
     *        1X,'TRANSITWAY IVT      =',F12.2/
     *        1X,'URBAN RAIL IVT      =',F12.2/
     *        1X,'COMMUTER RAIL IVT   =',F12.2/
     *        1X,'FARE                =',F12.2/
     *        1X,'RAPID BUS IVT       =',F12.2/
     *        1X,'BRT IVT             =',F12.2/)
      END IF
C -----------------------------------------------------------------------
      RETURN
      END
