C ------------------------------------------------------------
C     STORE TOLL FACILITY VALUES
C ------------------------------------------------------------
      SUBROUTINE TSUM(TOLLSUM,INDC,TRIPS,TYPE,TOLLTLF,DIST1,DIST2,
     *                TOLLSAV,TMESAV)
      REAL*8        TOLLSUM(9,10),TRIPS,TOLLTLF(102,9,13)
      REAL*8        TOLLSAV(31,9,10)
      REAL*4        DIST1,DIST2
      INTEGER*2     TMESAV(10)
      INTEGER*4     INDC,TYPE,TINDEX,HTYPE
C
C     SUMMARIZE TRIPS BY FACILITY
C
      IF(INDC.GT.0) THEN
      TOLLSUM(INDC,TYPE)=TOLLSUM(INDC,TYPE)+TRIPS
      ELSE
      TOLLSUM(8,TYPE)=TOLLSUM(8,TYPE)+TRIPS
      END IF
C
C     SUMMARIZE TRIP LENGTH FREQUENCY DISTRIBUTION
C
      TINDEX=IFIX(DIST1)+1
      IF(TINDEX.LT.1.OR.TINDEX.GT.101) THEN
C     WRITE(26,8001) DIST1,TYPE
 8001 FORMAT(' ENCOUNTERED TOLL/HOV LANE DISTANCE (',F6.2,
     *       ') GREATER THAN 100 MILES FOR TYPE=',I2)
      TINDEX=101
      END IF
      IF(DIST1.EQ.0.0) TINDEX=102
      IF(INDC.GT.0) THEN
      TOLLTLF(TINDEX,INDC,TYPE)=TOLLTLF(TINDEX,INDC,TYPE)+TRIPS
      ELSE
      TOLLTLF(TINDEX,8,TYPE)=TOLLTLF(TINDEX,8,TYPE)+TRIPS      
      END IF
C...
      IF(TYPE.EQ.3.OR.TYPE.EQ.6.OR.TYPE.EQ.9) THEN
      HTYPE=11
      IF(TYPE.EQ.6) HTYPE=12
      IF(TYPE.EQ.9) HTYPE=13
      TINDEX=IFIX(DIST2)+1
      IF(TINDEX.LT.1.OR.TINDEX.GT.101) THEN
C     WRITE(26,8002) DIST2,TYPE
 8002 FORMAT(' ENCOUNTERED HOV LANE DISTANCE (',F6.2,
     *       ') GREATER THAN 100 MILES FOR TYPE=',I2)
      TINDEX=101
      END IF
      IF(DIST2.EQ.0.0) TINDEX=102
      IF(INDC.GT.0) THEN
      TOLLTLF(TINDEX,INDC,HTYPE)=TOLLTLF(TINDEX,INDC,HTYPE)+TRIPS
      ELSE
      TOLLTLF(TINDEX,8,HTYPE)=TOLLTLF(TINDEX,8,HTYPE)+TRIPS      
      END IF
      END IF
C
C     SUMMARIZE TIME SAVINGS PER MILE
C
      IF(TYPE.EQ.2.OR.TYPE.EQ.5.OR.TYPE.EQ.8) RETURN
      IF(INDC.GT.0) THEN
      TOLLSAV(TMESAV(TYPE),INDC,TYPE)=
     *     TOLLSAV(TMESAV(TYPE),INDC,TYPE)+TRIPS
      ELSE
      TOLLSAV(TMESAV(TYPE),8,TYPE)=
     *     TOLLSAV(TMESAV(TYPE),8,TYPE)+TRIPS
      END IF
      RETURN
      END
